### ISSUE TITLE
Public Implementation

### ISSUE THREAD

**Issue by Aliiiqbp** [jprokos1/breaking-perceptual-hashing#7]
Hi,

I wanted to express my appreciation for your great work.

I am currently working on perceptual hash methods, as well as attacks and defenses in this domain. I was wondering if you would be willing to share your implementations on this work, as I believe they would be a valuable resource for my research.

Thank you for your time,

**Comment by jprokos1** [comment]
I cannot release our attack code publicly as the PhotoDNA code is not public for us to share; I have reached out separately to help you out.

**Comment by Aliiiqbp** [comment]
Thank you so much. I deeply appreciate it.
